CREATE DATABASE `Music` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `Artists` (
  `ArtistID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(35) NOT NULL,
  PRIMARY KEY (`ArtistID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;


CREATE TABLE `Albums` (
  `AlbumID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(35) NOT NULL,
  `ArtistID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AlbumID`),
  KEY `ArtistID_idx` (`ArtistID`),
  CONSTRAINT `ArtistID` FOREIGN KEY (`ArtistID`) REFERENCES `Artists` (`ArtistID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;


CREATE TABLE `Songs` (
  `SongID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(35) NOT NULL,
  `Duration` varchar(10) DEFAULT NULL,
  `AlbumID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SongID`),
  KEY `AlbumID_idx` (`AlbumID`),
  CONSTRAINT `AlbumID` FOREIGN KEY (`AlbumID`) REFERENCES `Albums` (`AlbumID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;


